info: Server started at http://localhost:5455/api/v1/ {"timestamp":"2023-03-09T04:54:46.879Z"}
info: Connected to the database. {"timestamp":"2023-03-09T04:54:47.014Z"}
error: 
    status - 500 
    message - Error: User already register with this email!
    at _callee2$ (E:\bookstore\src\services\/user.service.js:35:11)
    at tryCatch (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/users/registerUser 
    method - POST 
    IP - ::1
   {"timestamp":"2023-03-09T05:03:37.174Z"}
info: Server started at http://localhost:5455/api/v1/ {"timestamp":"2023-03-09T05:16:03.725Z"}
info: Connected to the database. {"timestamp":"2023-03-09T05:16:03.826Z"}
info: Connected to the database. {"timestamp":"2023-03-09T05:16:03.916Z"}
info: Server started at http://localhost:5455/api/v1/ {"timestamp":"2023-03-09T05:16:42.629Z"}
info: Connected to the database. {"timestamp":"2023-03-09T05:16:42.701Z"}
error: 
    status - 500 
    message - Error: Invalid Object_id
    at _callee3$ (E:\bookstore\src\services\/cart.service.js:103:11)
    at tryCatch (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/cart/purchased 
    method - POST 
    IP - ::1
   {"timestamp":"2023-03-09T05:21:26.285Z"}
info: Server started at http://localhost:5455/api/v1/ {"timestamp":"2023-03-09T05:22:27.815Z"}
info: Connected to the database. {"timestamp":"2023-03-09T05:22:27.857Z"}
error: 
    status - 500 
    message - Error: Invalid Object_id
    at _callee3$ (E:\bookstore\src\services\/cart.service.js:103:11)
    at tryCatch (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/cart/purchased/64086c27f3340d314c654e05 
    method - POST 
    IP - ::1
   {"timestamp":"2023-03-09T05:24:52.967Z"}
error: 
    status - 500 
    message - Error: Invalid Object_id
    at _callee3$ (E:\bookstore\src\services\/cart.service.js:103:11)
    at tryCatch (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/cart/purchased/6403153f24cd88467ce591c2 
    method - POST 
    IP - ::1
   {"timestamp":"2023-03-09T05:25:46.299Z"}
error: 
    status - 500 
    message - Error: Book already is in Wishlist 
    at _callee$ (E:\bookstore\src\services\/wishList.service.js:36:23)
    at tryCatch (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/wishList/add/621588d505253301a4fda5cf 
    method - POST 
    IP - ::1
   {"timestamp":"2023-03-09T05:28:15.782Z"}
error: 
    status - 500 
    message - Error: Book does't not exists in wishList
    at _callee2$ (E:\bookstore\src\services\/wishList.service.js:55:19)
    at tryCatch (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/wishList/remove/621588af05253301a4fda5ce 
    method - POST 
    IP - ::1
   {"timestamp":"2023-03-09T05:29:21.954Z"}
error: 
    status - 500 
    message - Error: No address found for user with this id
    at _callee2$ (E:\bookstore\src\services\/customerDetails.service.js:51:19)
    at tryCatch (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\bookstore\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\bookstore\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/customerDetails/64096f3fa4a4723294a10cca 
    method - PUT 
    IP - ::1
   {"timestamp":"2023-03-09T05:34:46.874Z"}
info: Server started at http://localhost:5455/api/v1/ {"timestamp":"2023-03-09T06:20:06.684Z"}
info: Connected to the database. {"timestamp":"2023-03-09T06:20:06.737Z"}
